CREATE TABLE IF NOT EXISTS b_kitconsulting_product_applications
(
    ID INT(18) UNSIGNED NOT NULL AUTO_INCREMENT,
    OWNER_PRODUCT_ID INT(1) NOT NULL,
    PRODUCT_ID INT(1) NOT NULL,
    PRIMARY KEY (ID)
)
